-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SERVICE_DESK
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SERVICE_DESK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SERVICE_DESK` DEFAULT CHARACTER SET utf8 ;
USE `SERVICE_DESK` ;

-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`TIPO_DOCUMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`TIPO_DOCUMENTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_DOCUMENTO` VARCHAR(45) NOT NULL,
  `ABREVIACION` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ABREVIACION_UNIQUE` (`ABREVIACION` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`TIPO_TECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`TIPO_TECNICO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_TECNICO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`TIPO_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`TIPO_CATEGORIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_CATEGORIA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`TIPO_CARACTERISTICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`TIPO_CARACTERISTICA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TIPO_CARACTERISTICA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`EQUIPO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`EQUIPO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_EQUIPO` VARCHAR(100) NOT NULL,
  `ACTIVO` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`PERSONA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_COMPLETO` VARCHAR(150) NOT NULL,
  `ID_TIPO_DOCUMENTO` INT NOT NULL,
  `NUMERO_DOCUMENTO` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NUMERO_DOCUMENTO_UNIQUE` (`NUMERO_DOCUMENTO` ASC) VISIBLE,
  INDEX `FK_TIPO_DOCUMENTO_PERSONA_idx` (`ID_TIPO_DOCUMENTO` ASC) VISIBLE,
  CONSTRAINT `FK_PERSONA_TIPO_DOCUMENTO`
    FOREIGN KEY (`ID_TIPO_DOCUMENTO`)
    REFERENCES `SERVICE_DESK`.`TIPO_DOCUMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`TECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`TECNICO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PERSONA` INT NOT NULL,
  `ID_TIPO_TECNICO` INT NOT NULL,
  `ACTIVO` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  INDEX `FK_TECNICO_PERSONA_idx` (`ID_PERSONA` ASC) VISIBLE,
  INDEX `FK_TECNICO_TIPO_TECNICO_idx` (`ID_TIPO_TECNICO` ASC) VISIBLE,
  CONSTRAINT `FK_TECNICO_PERSONA`
    FOREIGN KEY (`ID_PERSONA`)
    REFERENCES `SERVICE_DESK`.`PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TECNICO_TIPO_TECNICO`
    FOREIGN KEY (`ID_TIPO_TECNICO`)
    REFERENCES `SERVICE_DESK`.`TIPO_TECNICO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`EQUIPO_PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`EQUIPO_PERSONA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_EQUIPO` INT NOT NULL,
  `ID_PERSONA` INT NOT NULL,
  `FECHA_INICIO` DATE NOT NULL,
  `FECHA_FIN` DATE NULL,
  `ACTIVO` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  INDEX `FK_EQUIPO_PERSONA_EQUIPO_idx` (`ID_EQUIPO` ASC) VISIBLE,
  INDEX `FK_EQUIPO_PERSONA_PERSONA_idx` (`ID_PERSONA` ASC) VISIBLE,
  CONSTRAINT `FK_EQUIPO_PERSONA_EQUIPO`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `SERVICE_DESK`.`EQUIPO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EQUIPO_PERSONA_PERSONA`
    FOREIGN KEY (`ID_PERSONA`)
    REFERENCES `SERVICE_DESK`.`PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`EQUIPO_CARACTERISTICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`EQUIPO_CARACTERISTICA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_EQUIPO` INT NOT NULL,
  `ID_TIPO_CARACTERISTICA` INT NOT NULL,
  `DESCRIPCION` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_EQUIPO_CARACTERISTICA_TIPO_CARACTERISTICA_idx` (`ID_TIPO_CARACTERISTICA` ASC) VISIBLE,
  INDEX `FK_EQUIPO_CARACTERISTICA_EQUIPO_idx` (`ID_EQUIPO` ASC) VISIBLE,
  CONSTRAINT `FK_EQUIPO_CARACTERISTICA_TIPO_CARACTERISTICA`
    FOREIGN KEY (`ID_TIPO_CARACTERISTICA`)
    REFERENCES `SERVICE_DESK`.`TIPO_CARACTERISTICA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EQUIPO_CARACTERISTICA_EQUIPO`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `SERVICE_DESK`.`EQUIPO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`INCIDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`INCIDENTE` (
  `ID` INT NOT NULL,
  `ID_TIPO_CATEGORIA` INT NOT NULL,
  `ID_EQUIPO` INT NOT NULL,
  `ID_PERSONA` INT NOT NULL,
  `FECHA_REGISTRA` DATE NOT NULL,
  `FINALIZADO` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  INDEX `FK_INCIDENTE_TIPO_CATEGORIA_idx` (`ID_TIPO_CATEGORIA` ASC) VISIBLE,
  INDEX `FK_INCIDENTE_EQUIPO_idx` (`ID_EQUIPO` ASC) VISIBLE,
  INDEX `FK_INCIDENTE_PERSONA_idx` (`ID_PERSONA` ASC) VISIBLE,
  CONSTRAINT `FK_INCIDENTE_TIPO_CATEGORIA`
    FOREIGN KEY (`ID_TIPO_CATEGORIA`)
    REFERENCES `SERVICE_DESK`.`TIPO_CATEGORIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INCIDENTE_EQUIPO`
    FOREIGN KEY (`ID_EQUIPO`)
    REFERENCES `SERVICE_DESK`.`EQUIPO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INCIDENTE_PERSONA`
    FOREIGN KEY (`ID_PERSONA`)
    REFERENCES `SERVICE_DESK`.`PERSONA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`INCIDENTE_TECNICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`INCIDENTE_TECNICO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_TECNICO` INT NOT NULL,
  `ID_INCIDENTE` INT NOT NULL,
  `NIVEL_ESCALAMIENTO` INT NOT NULL,
  `FECHA_REGISTRO` DATE NOT NULL,
  `ACTIVO` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`),
  INDEX `FK_INCIDENTE_TECNICO_TECNICO_idx` (`ID_TECNICO` ASC) VISIBLE,
  INDEX `FK_INCIDENTE_TECNICO_INCIDENTE_idx` (`ID_INCIDENTE` ASC) VISIBLE,
  CONSTRAINT `FK_INCIDENTE_TECNICO_TECNICO`
    FOREIGN KEY (`ID_TECNICO`)
    REFERENCES `SERVICE_DESK`.`TECNICO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_INCIDENTE_TECNICO_INCIDENTE`
    FOREIGN KEY (`ID_INCIDENTE`)
    REFERENCES `SERVICE_DESK`.`INCIDENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SERVICE_DESK`.`OBSERVACION_INCIDENCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SERVICE_DESK`.`OBSERVACION_INCIDENCIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_INCIDENTE_TECNICO` INT NOT NULL,
  `OBSERVACION` VARCHAR(500) NOT NULL,
  `FECHA_REGISTRA` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_OBSERVACION_INCIDENCIA_INCIDENTE_TECNICO_idx` (`ID_INCIDENTE_TECNICO` ASC) VISIBLE,
  CONSTRAINT `FK_OBSERVACION_INCIDENCIA_INCIDENTE_TECNICO`
    FOREIGN KEY (`ID_INCIDENTE_TECNICO`)
    REFERENCES `SERVICE_DESK`.`INCIDENTE_TECNICO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SERVICE_DESK`.`TIPO_DOCUMENTO`
-- -----------------------------------------------------
START TRANSACTION;
USE `SERVICE_DESK`;
INSERT INTO `SERVICE_DESK`.`TIPO_DOCUMENTO` (`ID`, `TIPO_DOCUMENTO`, `ABREVIACION`) VALUES (1, 'Cédula de Ciudadanía', 'CC');
INSERT INTO `SERVICE_DESK`.`TIPO_DOCUMENTO` (`ID`, `TIPO_DOCUMENTO`, `ABREVIACION`) VALUES (2, 'Tarjeta de Identidad', 'TI');
INSERT INTO `SERVICE_DESK`.`TIPO_DOCUMENTO` (`ID`, `TIPO_DOCUMENTO`, `ABREVIACION`) VALUES (3, 'Pasaporte', 'PP');
INSERT INTO `SERVICE_DESK`.`TIPO_DOCUMENTO` (`ID`, `TIPO_DOCUMENTO`, `ABREVIACION`) VALUES (4, 'Cédula de Extranjería', 'CE');

COMMIT;

